# Generated by Django 3.2.5 on 2021-08-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
